const std = @import("std");
const Io = @import("../../util/io.zig").Io;

pub fn execute(allocator: std.mem.Allocator, args: []const []const u8, io: Io) !void {
    var shell: ?[]const u8 = null;

    for (args) |arg| {
        if (std.mem.eql(u8, arg, "--help") or std.mem.eql(u8, arg, "-h")) {
            try printHelp(io);
            return;
        } else if (std.mem.eql(u8, arg, "bash")) {
            shell = "bash";
        } else if (std.mem.eql(u8, arg, "zsh")) {
            shell = "zsh";
        } else if (std.mem.eql(u8, arg, "fish")) {
            shell = "fish";
        }
    }

    const s = shell orelse {
        try io.eprint("usage: gitz completions <shell>\n\n", .{});
        try io.eprint("Generate shell completions for gitz.\n\n", .{});
        try io.eprint("Supported shells:\n", .{});
        try io.eprint("  bash    Generate bash completions\n", .{});
        try io.eprint("  zsh     Generate zsh completions\n", .{});
        try io.eprint("  fish    Generate fish completions\n", .{});
        try io.eprint("\nTo install:\n", .{});
        try io.eprint("  eval \"$(gitz completions bash)\"       # Bash\n", .{});
        try io.eprint("  eval \"$(gitz completions zsh)\"        # Zsh\n", .{});
        try io.eprint("  gitz completions fish | source        # Fish\n", .{});
        return;
    };

    if (std.mem.eql(u8, s, "bash")) {
        try generateBash(allocator, io);
    } else if (std.mem.eql(u8, s, "zsh")) {
        try generateZsh(allocator, io);
    } else if (std.mem.eql(u8, s, "fish")) {
        try generateFish(allocator, io);
    }
}

fn printHelp(io: Io) !void {
    try io.print(
        \\usage: gitz completions <shell>
        \\
        \\Generate shell completions for gitz.
        \\
        \\Supported shells:
        \\  bash    Generate bash completions
        \\  zsh     Generate zsh completions
        \\  fish    Generate fish completions
        \\
        \\To install:
        \\  eval "$(gitz completions bash)"       # Bash
        \\  eval "$(gitz completions zsh)"        # Zsh
        \\  gitz completions fish | source        # Fish
        \\
    , .{});
}

fn generateBash(allocator: std.mem.Allocator, io: Io) !void {
    _ = allocator;
    const script =
        \\# Bash completions for gitz
        \\# Generated by gitz completions bash
        \\
        \\_gitz_completions() {
        \\    local cur prev commands
        \\    COMPREPLY=()
        \\    cur="${COMP_WORDS[COMP_CWORD]}"
        \\    prev="${COMP_WORDS[COMP_CWORD-1]}"
        \\
        \\    commands="init add commit status diff log branch switch merge rebase stash reset undo tag blame gc config search review sync lfs clone fetch push pull remote update completions"
        \\
        \\    local subcommands
        \\    case "$prev" in
        \\        add)            COMPREPLY=($(compgen -f -- "$cur")); return 0 ;;
        \\        commit)
        \\            case "$cur" in
        \\                -*) COMPREPLY=($(compgen -W "-m -a --amend --help" -- "$cur")) ;;
        \\                *)  COMPREPLY=($(compgen -f -- "$cur")) ;;
        \\            esac
        \\            return 0 ;;
        \\        log)
        \\            COMPREPLY=($(compgen -W "--oneline --graph --all -n --author= --grep= --help" -- "$cur"))
        \\            return 0 ;;
        \\        branch)
        \\            case "$cur" in
        \\                -*) COMPREPLY=($(compgen -W "-d -D -m --help" -- "$cur")) ;;
        \\                *)  _gitz_branches; return 0 ;;
        \\            esac ;;
        \\        switch)
        \\            case "$cur" in
        \\                -*) COMPREPLY=($(compgen -W "-c --help" -- "$cur")) ;;
        \\                *)  _gitz_branches; return 0 ;;
        \\            esac ;;
        \\        diff)
        \\            COMPREPLY=($(compgen -W "--staged --help" -- "$cur"))
        \\            return 0 ;;
        \\        stash)
        \\            COMPREPLY=($(compgen -W "push pop apply list drop show --help" -- "$cur"))
        \\            return 0 ;;
        \\        reset)
        \\            COMPREPLY=($(compgen -W "--soft --mixed --hard --help" -- "$cur"))
        \\            return 0 ;;
        \\        rebase)
        \\            COMPREPLY=($(compgen -W "-i --abort --onto --continue --help" -- "$cur"))
        \\            return 0 ;;
        \\        merge)
        \\            COMPREPLY=($(compgen -W "--no-ff --help" -- "$cur"))
        \\            return 0 ;;
        \\        tag)
        \\            case "$cur" in
        \\                -*) COMPREPLY=($(compgen -W "-a -d -m --help" -- "$cur")) ;;
        \\                *)  COMPREPLY=($(compgen -W "$(gitz tag 2>/dev/null)" -- "$cur")) ;;
        \\            esac
        \\            return 0 ;;
        \\        remote)
        \\            COMPREPLY=($(compgen -W "add remove list set-url --help" -- "$cur"))
        \\            return 0 ;;
        \\        clone)         COMPREPLY=($(compgen -f -- "$cur")); return 0 ;;
        \\        fetch)
        \\            COMPREPLY=($(compgen -W "--git -g --help" -- "$cur"))
        \\            return 0 ;;
        \\        push)
        \\            COMPREPLY=($(compgen -W "--git -g --force --help" -- "$cur"))
        \\            return 0 ;;
        \\        pull)
        \\            COMPREPLY=($(compgen -W "--merge --rebase --git -g --help" -- "$cur"))
        \\            return 0 ;;
        \\        config)
        \\            COMPREPLY=($(compgen -W "user.name user.email --list --help" -- "$cur"))
        \\            return 0 ;;
        \\        search)
        \\            COMPREPLY=($(compgen -W "-c --content -m --message --all -n -C --author= --help" -- "$cur"))
        \\            return 0 ;;
        \\        review)
        \\            COMPREPLY=($(compgen -W "--stat --summary --no-stat --help" -- "$cur"))
        \\            return 0 ;;
        \\        sync)
        \\            COMPREPLY=($(compgen -W "--force -f --git -g --help" -- "$cur"))
        \\            return 0 ;;
        \\        lfs)
        \\            COMPREPLY=($(compgen -W "install track untrack status ls pointer env --help" -- "$cur"))
        \\            return 0 ;;
        \\    esac
        \\
        \\    if [[ "$cur" == -* ]] ; then
        \\        COMPREPLY=($(compgen -W "-h --help -v --version" -- "$cur"))
        \\        return 0
        \\    fi
        \\
        \\    COMPREPLY=($(compgen -W "$commands" -- "$cur"))
        \\    return 0
        \\}
        \\
        \\_gitz_branches() {
        \\    local branches
        \\    branches=$(gitz branch 2>/dev/null | sed 's/^[* ]*//')
        \\    COMPREPLY=($(compgen -W "$branches" -- "${COMP_WORDS[COMP_CWORD]}"))
        \\}
        \\
        \\complete -F _gitz_completions gitz
        \\
    ;
    try io.print("{s}", .{script});
}

fn generateZsh(allocator: std.mem.Allocator, io: Io) !void {
    _ = allocator;
    const script =
        \\# Zsh completions for gitz
        \\# Generated by gitz completions zsh
        \\
        \\#compdef gitz
        \\
        \\_gitz() {
        \\    local -a commands
        \\    commands=(
        \\        'init:Initialize a new repository'
        \\        'add:Stage files for commit'
        \\        'commit:Record changes to the repository'
        \\        'status:Show working tree status'
        \\        'diff:Show changes between commits'
        \\        'log:Show commit history'
        \\        'branch:List, create, or delete branches'
        \\        'switch:Switch to a branch or create a new one'
        \\        'merge:Join two branches together'
        \\        'rebase:Reapply commits on top of another base'
        \\        'stash:Stash changes in a dirty working directory'
        \\        'reset:Reset current HEAD to a specified state'
        \\        'undo:Undo the last commit'
        \\        'tag:Create, list, delete tags'
        \\        'blame:Show what revision and author last modified each line'
        \\        'gc:Clean up unreachable objects'
        \\        'config:Get and set repository options'
        \\        'search:Search commit messages and file contents'
        \\        'review:Code review (diff between branches/commits)'
        \\        'sync:Fetch and rebase onto remote branch'
        \\        'lfs:Git Large File Storage'
        \\        'clone:Clone a repository from a URL'
        \\        'fetch:Download objects and refs from a remote'
        \\        'push:Update remote refs using associated local objects'
        \\        'pull:Fetch from and integrate with another repository'
        \\        'remote:Manage set of tracked repositories'
        \\        'update:Update gitz to the latest version'
        \\        'completions:Generate shell completions'
        \\    )
        \\
        \\    local -a subcmds
        \\    case ${words[2]} in
        \\        add)
        \\            _files
        \\            ;;
        \\        commit)
        \\            _arguments \
        \\                '-m[Set commit message]' \
        \\                '-a[Auto-stage all modified files]' \
        \\                '--amend[Modify last commit]' \
        \\                '--help[Show help]'
        \\            ;;
        \\        log)
        \\            _arguments \
        \\                '--oneline[Show one line per commit]' \
        \\                '--graph[Show ASCII graph]' \
        \\                '--all[Show all branches]' \
        \\                '-n[Limit count]:count:' \
        \\                '--author=[Filter by author]:author:' \
        \\                '--grep=[Filter by message]:grep:'
        \\            ;;
        \\        branch)
        \\            _arguments \
        \\                '-d[Delete branch]' \
        \\                '-D[Force delete branch]' \
        \\                '-m[Rename branch]' \
        \\                '--help[Show help]'
        \\            ;;
        \\        switch)
        \\            _arguments \
        \\                '-c[Create and switch to new branch]' \
        \\                '--help[Show help]'
        \\            ;;
        \\        diff)
        \\            _arguments \
        \\                '--staged[Show staged changes]' \
        \\                '--help[Show help]'
        \\            ;;
        \\        stash)
        \\            _arguments '1:command:(push pop apply list drop show)'
        \\            ;;
        \\        reset)
        \\            _arguments \
        \\                '--soft[Move HEAD, keep staged]' \
        \\                '--mixed[Move HEAD, unstage]' \
        \\                '--hard[Move HEAD, discard working tree]' \
        \\                '--help[Show help]'
        \\            ;;
        \\        rebase)
        \\            _arguments \
        \\                '-i[Interactive rebase]' \
        \\                '--abort[Cancel rebase]' \
        \\                '--onto[Rebase with custom base]' \
        \\                '--continue[Continue rebase]' \
        \\                '--help[Show help]'
        \\            ;;
        \\        merge)
        \\            _arguments \
        \\                '--no-ff[Create merge commit]' \
        \\                '--help[Show help]'
        \\            ;;
        \\        tag)
        \\            _arguments \
        \\                '-a[Create annotated tag]' \
        \\                '-d[Delete tag]' \
        \\                '-m[Set tag message]' \
        \\                '--help[Show help]'
        \\            ;;
        \\        remote)
        \\            _arguments '1:command:(add remove list set-url)'
        \\            ;;
        \\        fetch)
        \\            _arguments \
        \\                '--git[Use system git]' \
        \\                '-g[Use system git]' \
        \\                '--help[Show help]'
        \\            ;;
        \\        push)
        \\            _arguments \
        \\                '--git[Use system git]' \
        \\                '-g[Use system git]' \
        \\                '--force[Force push]' \
        \\                '--help[Show help]'
        \\            ;;
        \\        pull)
        \\            _arguments \
        \\                '--merge[Use merge instead of rebase]' \
        \\                '--rebase[Use rebase (default)]' \
        \\                '--git[Use system git]' \
        \\                '-g[Use system git]' \
        \\                '--help[Show help]'
        \\            ;;
        \\        config)
        \\            _arguments \
        \\                '--list[List all config]' \
        \\                '--help[Show help]'
        \\            ;;
        \\        search)
        \\            _arguments \
        \\                '-c[Search file contents]' \
        \\                '--content[Search file contents]' \
        \\                '-m[Search commit messages]' \
        \\                '--message[Search commit messages]' \
        \\                '--all[Search both messages and content]' \
        \\                '-n[Max commits to search]:count:' \
        \\                '-C[Context lines for content matches]:lines:' \
        \\                '--author=[Filter by author]:author:' \
        \\                '--help[Show help]'
        \\            ;;
        \\        review)
        \\            _arguments \
        \\                '--stat[Show stats only]' \
        \\                '--summary[Summary only]' \
        \\                '--no-stat[No stats]' \
        \\                '--help[Show help]'
        \\            ;;
        \\        sync)
        \\            _arguments \
        \\                '--force[Force push after sync]' \
        \\                '-f[Force push after sync]' \
        \\                '--git[Use system git]' \
        \\                '-g[Use system git]' \
        \\                '--help[Show help]'
        \\            ;;
        \\        lfs)
        \\            _arguments '1:command:(install track untrack status ls pointer env)'
        \\            ;;
        \\        completions)
        \\            _arguments '1:shell:(bash zsh fish)'
        \\            ;;
        \\        *)
        \\            _describe -t commands 'gitz command' commands
        \\            ;;
        \\    esac
        \\}
        \\
        \\_gitz "$@"
        \\
    ;
    try io.print("{s}", .{script});
}

fn generateFish(allocator: std.mem.Allocator, io: Io) !void {
    _ = allocator;
    const script =
        \\# Fish completions for gitz
        \\# Generated by gitz completions fish
        \\
        \\# Helper: complete subcommands
        \\function __gitz_needs_command
        \\    set -l cmd (commandline -opc)
        \\    test (count $cmd) -eq 1
        \\end
        \\
        \\function __gitz_using_command
        \\    set -l cmd (commandline -opc)
        \\    test (count $cmd) -gt 1; and test "$cmd[2]" = "$argv[1]"
        \\end
        \\
        \\# Main commands
        \\complete -c gitz -n __gitz_needs_command -a init -d 'Initialize a new repository'
        \\complete -c gitz -n __gitz_needs_command -a add -d 'Stage files for commit'
        \\complete -c gitz -n __gitz_needs_command -a commit -d 'Record changes to the repository'
        \\complete -c gitz -n __gitz_needs_command -a status -d 'Show working tree status'
        \\complete -c gitz -n __gitz_needs_command -a diff -d 'Show changes between commits'
        \\complete -c gitz -n __gitz_needs_command -a log -d 'Show commit history'
        \\complete -c gitz -n __gitz_needs_command -a branch -d 'List, create, or delete branches'
        \\complete -c gitz -n __gitz_needs_command -a switch -d 'Switch to a branch or create a new one'
        \\complete -c gitz -n __gitz_needs_command -a merge -d 'Join two branches together'
        \\complete -c gitz -n __gitz_needs_command -a rebase -d 'Reapply commits on top of another base'
        \\complete -c gitz -n __gitz_needs_command -a stash -d 'Stash changes in a dirty working directory'
        \\complete -c gitz -n __gitz_needs_command -a reset -d 'Reset current HEAD to a specified state'
        \\complete -c gitz -n __gitz_needs_command -a undo -d 'Undo the last commit'
        \\complete -c gitz -n __gitz_needs_command -a tag -d 'Create, list, delete tags'
        \\complete -c gitz -n __gitz_needs_command -a blame -d 'Show what revision and author last modified each line'
        \\complete -c gitz -n __gitz_needs_command -a gc -d 'Clean up unreachable objects'
        \\complete -c gitz -n __gitz_needs_command -a config -d 'Get and set repository options'
        \\complete -c gitz -n __gitz_needs_command -a search -d 'Search commit messages and file contents'
        \\complete -c gitz -n __gitz_needs_command -a review -d 'Code review (diff between branches/commits)'
        \\complete -c gitz -n __gitz_needs_command -a sync -d 'Fetch and rebase onto remote branch'
        \\complete -c gitz -n __gitz_needs_command -a lfs -d 'Git Large File Storage'
        \\complete -c gitz -n __gitz_needs_command -a clone -d 'Clone a repository from a URL'
        \\complete -c gitz -n __gitz_needs_command -a fetch -d 'Download objects and refs from a remote'
        \\complete -c gitz -n __gitz_needs_command -a push -d 'Update remote refs using associated local objects'
        \\complete -c gitz -n __gitz_needs_command -a pull -d 'Fetch from and integrate with another repository'
        \\complete -c gitz -n __gitz_needs_command -a remote -d 'Manage set of tracked repositories'
        \\complete -c gitz -n __gitz_needs_command -a update -d 'Update gitz to the latest version'
        \\complete -c gitz -n __gitz_needs_command -a completions -d 'Generate shell completions'
        \\
        \\# Global options
        \\complete -c gitz -s h -l help -d 'Show help'
        \\complete -c gitz -s v -l version -d 'Show version'
        \\
        \\# commit options
        \\complete -c gitz -n '__gitz_using_command commit' -s m -d 'Set commit message'
        \\complete -c gitz -n '__gitz_using_command commit' -s a -d 'Auto-stage all modified files'
        \\complete -c gitz -n '__gitz_using_command commit' -l amend -d 'Modify last commit'
        \\
        \\# log options
        \\complete -c gitz -n '__gitz_using_command log' -l oneline -d 'Show one line per commit'
        \\complete -c gitz -n '__gitz_using_command log' -l graph -d 'Show ASCII graph'
        \\complete -c gitz -n '__gitz_using_command log' -l all -d 'Show all branches'
        \\complete -c gitz -n '__gitz_using_command log' -s n -d 'Limit count'
        \\complete -c gitz -n '__gitz_using_command log' -l author -d 'Filter by author'
        \\complete -c gitz -n '__gitz_using_command log' -l grep -d 'Filter by message'
        \\
        \\# branch options
        \\complete -c gitz -n '__gitz_using_command branch' -s d -d 'Delete branch'
        \\complete -c gitz -n '__gitz_using_command branch' -s D -d 'Force delete branch'
        \\complete -c gitz -n '__gitz_using_command branch' -s m -d 'Rename branch'
        \\
        \\# switch options
        \\complete -c gitz -n '__gitz_using_command switch' -s c -d 'Create and switch to new branch'
        \\
        \\# diff options
        \\complete -c gitz -n '__gitz_using_command diff' -l staged -d 'Show staged changes'
        \\
        \\# stash subcommands
        \\complete -c gitz -n '__gitz_using_command stash' -a push -d 'Save changes'
        \\complete -c gitz -n '__gitz_using_command stash' -a pop -d 'Apply and remove stash'
        \\complete -c gitz -n '__gitz_using_command stash' -a apply -d 'Apply stash'
        \\complete -c gitz -n '__gitz_using_command stash' -a list -d 'List stashes'
        \\complete -c gitz -n '__gitz_using_command stash' -a drop -d 'Drop a stash'
        \\complete -c gitz -n '__gitz_using_command stash' -a show -d 'Show stash contents'
        \\
        \\# reset options
        \\complete -c gitz -n '__gitz_using_command reset' -l soft -d 'Move HEAD, keep staged'
        \\complete -c gitz -n '__gitz_using_command reset' -l mixed -d 'Move HEAD, unstage'
        \\complete -c gitz -n '__gitz_using_command reset' -l hard -d 'Move HEAD, discard working tree'
        \\
        \\# rebase options
        \\complete -c gitz -n '__gitz_using_command rebase' -s i -d 'Interactive rebase'
        \\complete -c gitz -n '__gitz_using_command rebase' -l abort -d 'Cancel rebase'
        \\complete -c gitz -n '__gitz_using_command rebase' -l onto -d 'Rebase with custom base'
        \\complete -c gitz -n '__gitz_using_command rebase' -l continue -d 'Continue rebase'
        \\
        \\# merge options
        \\complete -c gitz -n '__gitz_using_command merge' -l no-ff -d 'Create merge commit'
        \\
        \\# tag options
        \\complete -c gitz -n '__gitz_using_command tag' -s a -d 'Create annotated tag'
        \\complete -c gitz -n '__gitz_using_command tag' -s d -d 'Delete tag'
        \\complete -c gitz -n '__gitz_using_command tag' -s m -d 'Set tag message'
        \\
        \\# remote subcommands
        \\complete -c gitz -n '__gitz_using_command remote' -a add -d 'Add a new remote'
        \\complete -c gitz -n '__gitz_using_command remote' -a remove -d 'Remove a remote'
        \\complete -c gitz -n '__gitz_using_command remote' -a list -d 'List remotes'
        \\complete -c gitz -n '__gitz_using_command remote' -a set-url -d 'Set remote URL'
        \\
        \\# fetch/push/pull options
        \\complete -c gitz -n '__gitz_using_command fetch' -l git -d 'Use system git'
        \\complete -c gitz -n '__gitz_using_command fetch' -s g -d 'Use system git'
        \\complete -c gitz -n '__gitz_using_command push' -l git -d 'Use system git'
        \\complete -c gitz -n '__gitz_using_command push' -s g -d 'Use system git'
        \\complete -c gitz -n '__gitz_using_command push' -l force -d 'Force push'
        \\complete -c gitz -n '__gitz_using_command pull' -l merge -d 'Use merge instead of rebase'
        \\complete -c gitz -n '__gitz_using_command pull' -l rebase -d 'Use rebase (default)'
        \\complete -c gitz -n '__gitz_using_command pull' -l git -d 'Use system git'
        \\complete -c gitz -n '__gitz_using_command pull' -s g -d 'Use system git'
        \\
        \\# config options
        \\complete -c gitz -n '__gitz_using_command config' -l list -d 'List all config'
        \\
        \\# search options
        \\complete -c gitz -n '__gitz_using_command search' -s c -l content -d 'Search file contents'
        \\complete -c gitz -n '__gitz_using_command search' -s m -l message -d 'Search commit messages'
        \\complete -c gitz -n '__gitz_using_command search' -l all -d 'Search both messages and content'
        \\complete -c gitz -n '__gitz_using_command search' -s n -d 'Max commits to search'
        \\complete -c gitz -n '__gitz_using_command search' -s C -d 'Context lines for content matches'
        \\complete -c gitz -n '__gitz_using_command search' -l author -d 'Filter by author'
        \\
        \\# review options
        \\complete -c gitz -n '__gitz_using_command review' -l stat -d 'Show stats only'
        \\complete -c gitz -n '__gitz_using_command review' -l summary -d 'Summary only'
        \\complete -c gitz -n '__gitz_using_command review' -l no-stat -d 'No stats'
        \\
        \\# sync options
        \\complete -c gitz -n '__gitz_using_command sync' -l force -s f -d 'Force push after sync'
        \\complete -c gitz -n '__gitz_using_command sync' -l git -s g -d 'Use system git'
        \\
        \\# lfs subcommands
        \\complete -c gitz -n '__gitz_using_command lfs' -a install -d 'Set up Git LFS'
        \\complete -c gitz -n '__gitz_using_command lfs' -a track -d 'Track large files'
        \\complete -c gitz -n '__gitz_using_command lfs' -a untrack -d 'Stop tracking large files'
        \\complete -c gitz -n '__gitz_using_command lfs' -a status -d 'Show LFS status'
        \\complete -c gitz -n '__gitz_using_command lfs' -a ls -d 'List LFS tracked files'
        \\complete -c gitz -n '__gitz_using_command lfs' -a pointer -d 'Show LFS pointer'
        \\complete -c gitz -n '__gitz_using_command lfs' -a env -d 'Show LFS environment'
        \\
        \\# completions subcommands
        \\complete -c gitz -n '__gitz_using_command completions' -a bash -d 'Generate bash completions'
        \\complete -c gitz -n '__gitz_using_command completions' -a zsh -d 'Generate zsh completions'
        \\complete -c gitz -n '__gitz_using_command completions' -a fish -d 'Generate fish completions'
        \\
    ;
    try io.print("{s}", .{script});
}
